apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db
  namespace: cnpg-system
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: openwebui-db
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "openwebui"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "6154cea9-a770-41e6-956e-b4a800f95bb9"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db
  namespace: openwebui
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: openwebui-db
    creationPolicy: Owner
    template:
      data:
        username: "openwebui"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "6154cea9-a770-41e6-956e-b4a800f95bb9"