ollama:
  enabled: false
pipelines:
  enabled: false

websocket:
  manager: ""
  redis:
    enabled: false

openaiBaseApiUrl: http://llamacpp-svc-proxy.llms.svc.cluster.local:8080/v1
openaiApiKey: no-key

extraEnvVars:
  - name: DATABASE_TYPE
    value: postgresql
  - name: DATABASE_HOST
    value: pg-cluster-rw.cnpg-system.svc.cluster.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: openwebui
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: openwebui-db
        key: username
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: openwebui-db
        key: password

persistence:
  enabled: true
  storageClass: longhorn-wdblack
  size: 10Gi

ingress:
  enabled: true
  class: tailscale
  annotations:
    tailscale.com/proxy-class: "tailscale-small"
  host: chat
  tls: true