apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: llamacpp
  namespace: llms
spec:
  target:
    service: llamacpp-svc
    port: 8080
  rules:
    - hosts:
        - genai
        - genai.tail2f38ea.ts.net
        - llamacpp-svc-proxy.llms
        - llamacpp-svc-proxy.llms.svc.cluster.local
  scalingMetric:
    concurrency:
      targetValue: 100
  timeouts:
    readiness: 300s
    request: 900s
    responseHeader: 300s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: llamacpp
  namespace: llms
spec:
  scaleTargetRef:
    name: llamacpp
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 1200
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: llamacpp