apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphiti
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/cunialino/myai.git'
      path: base/graphiti
      targetRevision: main
    - repoURL: 'https://github.com/cunialino/myai.git'
      path: base/llamacpp-graphiti
      targetRevision: main
    - repoURL: 'https://github.com/cunialino/myai.git'
      path: base/llamacpp-embed
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: graphiti
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true